style:review,mypage수정, 카운트 추가
nninyeong/challenge-b pull request #207
Opened 2024-11-18 14:26 UTC by sHyunis

## ✅ 작업 사항

- 리뷰페이지 수정사항 반영
: 도움돼요 => 좋아요 변환
: 좋아요 레이아웃 변경
: 리뷰 남은 이미지 숫자 표시

- 마이페이지
- 원형 프로그래스바 테두리 변경
- 레이아웃변경

## 📸 스크린샷
<img width="373" alt="스크린샷 2024-11-18 오후 11 22 41" src="https://github.com/user-attachments/assets/effee4af-47fc-4853-bcbd-3e51be845fa4">
<img width="383" alt="스크린샷 2024-11-18 오후 11 22 27" src="https://github.com/user-attachments/assets/98858131-10d4-4f97-8119-2d8050ab7a1f">
<br/>

## 🧑‍💻 기타

-

2024-11-18 15:23 UTC, Leekee0905 reviewed
👍👍👍

2024-11-18 15:28 UTC, nninyeong requested changes
고생하셨습니다! svg 옵션만 한번 확인해주세요!

2024-11-18 15:28 UTC, nninyeong commented on src/components/icons/HeartIcon.tsx
> +        stroke-linejoin='round'
여기 카멜케이스로 작성해주세요! 동작에 문제는 없는데 경고 로그가 꽤 길어요 ㅠㅠ

2024-11-18 15:28 UTC, nninyeong commented on src/components/icons/HeartIcon.tsx
> +        stroke-linejoin='round'
아래에 stop-color도 아마 바꿔도 동작할 것 같아요! 확인 한 번 부탁드릴게용!

2024-11-19 00:53 UTC, hansub1n approved these changes
..너무 러블리해요(아앗..! 로딩 ui~~~~~~)

2024-11-19 02:16 UTC, Leekee0905 approved these changes
approve!

2024-11-19 02:16 UTC, nninyeong approved these changes

2024-11-19 02:17 UTC, merged