Feat/main photo preview
nninyeong/challenge-b pull request #30
Opened 2024-10-28 07:17 UTC by sHyunis

## ✅ 작업 사항

- 경로 오류 수정

## 📸 스크린샷

<br/>

## 🧑‍💻 기타

-

2024-10-28 09:23 UTC, nninyeong requested changes

2024-10-28 09:23 UTC, nninyeong commented on src/app/mypage/page.tsx
> +  const profileUrl = user?.user?.user_metadata?.avatar_url || "/images/defaultImg.jpg";
여기 프리티어 적용이 안된 것 같아요! 작은따옴표로 변경돼야하지 않나용??

2024-10-29 02:32 UTC, Leekee0905 approved these changes

2024-10-29 02:32 UTC, Leekee0905 commented on src/app/create/card/page.tsx
> +  console.log(selectedFont);
console.log 지우고 올려주시면 좋을것같습니당

2024-10-29 03:22 UTC, nninyeong approved these changes
고생하셨습니다!

2024-10-29 03:23 UTC, merged